services:
  backend:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      database:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
      redis:
        condition: service_started
    expose:
      - '8000'
    ports:
      - '8000:8000'
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - '3000:3000'
    networks:
      - webnet
    volumes:
      - ./frontend:/app
      - node_modules_volume:/app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NODE_ENV=development
    command: pnpm dev

  celery:
    build:
      context: ./backend
    command: celery -A transcribe worker -l info
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
      - media_volume:/app/mediafiles
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - webnet

  celery-beat:
    build:
      context: ./backend
    command: celery -A transcribe beat -l info
    volumes:
      - ./backend:/app
      - celery_beat_logs:/var/log/celery
    env_file:
      - ./.env
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - webnet

  database:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    networks:
      - webnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:6
    networks:
      - webnet

  migrations:
    build:
      context: ./backend
    command: python manage.py migrate && python manage.py collectstatic --noinput
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
  static_volume:
  media_volume:
  celery_beat_logs:
  node_modules_volume:

networks:
  webnet: