version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - trane_network

  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      # The DSP service URL is set to the hostname "dsp" (as defined below)
      - DSP_SERVICE_URL=http://dsp:9000
      - DJANGO_SETTINGS_MODULE=trane.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - trane_network

  dsp:
    build:
      context: ./backend
      dockerfile: Dockerfile.dsp
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=trane.settings
      - PYTHONPATH=/app
      - FLASK_APP=trane.realtime_dsp.dsp_service
      - FLASK_ENV=development
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      # Add environment variables for performance tuning
      - LIBROSA_CACHE_DIR=/tmp/librosa_cache
      - OMP_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - MKL_NUM_THREADS=1
    # Add resource constraints
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - trane_network

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.dsp
    # Run as non-root user with proper permissions
    user: "1000:1000"  # Use standard user ID instead of 'nobody'
    command: celery -A trane worker --loglevel=info --concurrency=2 -O fair
    volumes:
      - ./backend:/app
      - /tmp/librosa_cache:/tmp/librosa_cache
      - /tmp/numba_cache:/tmp/numba_cache
    environment:
      - DJANGO_SETTINGS_MODULE=trane.settings
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      # Add environment variables for performance tuning
      - LIBROSA_CACHE_DIR=/tmp/librosa_cache
      - NUMBA_CACHE_DIR=/tmp/numba_cache
      - NUMBA_DISABLE_JIT=1
      - OMP_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      # Add Celery configuration
      - CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP=true
      - C_FORCE_ROOT=false
    # Add resource constraints
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    depends_on:
      redis:
        condition: service_healthy
      dsp:
        condition: service_started
    networks:
      - trane_network

networks:
  trane_network:
    driver: bridge

volumes:
  redis_data:
