# Generated by Django 5.1.6 on 2025-02-15 02:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('processing_time', models.FloatField()),
                ('queue_length', models.IntegerField()),
                ('gpu_memory_used', models.FloatField(blank=True, null=True)),
                ('gpu_utilization', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='realtime_ds_timesta_c1cdfd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('task_type', models.CharField(choices=[('audio', 'Audio Processing'), ('midi', 'MIDI Processing'), ('feature', 'Feature Extraction')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['task_type', 'status'], name='realtime_ds_task_ty_54d3df_idx'), models.Index(fields=['created_at'], name='realtime_ds_created_6481d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.JSONField()),
                ('metadata', models.JSONField(default=dict)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('processing_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='realtime_dsp.processingtask')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='realtime_ds_created_49c802_idx')],
            },
        ),
    ]
