# Generated by Django 5.1.3 on 2024-11-19 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='entry',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='output_directory',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='entries', to='core.document'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='entries', to='core.note'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['processing_status', 'priority'], name='core_entry_process_ae3cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['user', '-created_at'], name='core_entry_user_id_cd066a_idx'),
        ),
    ]
